name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install prettier
        # We don't want to save prettier as a dependency, so we use --no-save
        run: npm install --no-save prettier

      - name: Run prettier
        run: npm run format:ci || echo "::error::remember to run 'pnpm run format', and commit again'"

