name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: pnpm/action-setup@v2
        with:
          version: 7.27.1
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile

      - name: Run prettier
        run: pnpm run format:ci || echo "::error::remember to run 'pnpm run format', and commit again'"

